#!/bin/bash

###############################################################################
# Accessibility
###############################################################################

# Use scroll gesture with the Ctrl (^) modifier key to zoom.
sudo defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
sudo defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

###############################################################################
# Dock
###############################################################################

# Automatically hide and show the Dock.
defaults write com.apple.dock autohide -bool false

# Change default size.
defaults write com.apple.dock tilesize -float 38

# Reorganize the Dock.
dockutil --no-restart --remove all
dockutil --no-restart --add "/Applications/Safari.app"
dockutil --no-restart --add "/Applications/Calendar.app"
dockutil --no-restart --add "/Applications/Visual Studio Code.app"
dockutil --no-restart --add "/Applications/Slack.app"
dockutil --no-restart --add "/Applications/iTerm.app"
dockutil --no-restart --add "/Applications/App Store.app"
dockutil --no-restart --add "/Applications/System Preferences.app"
dockutil --no-restart --add "/Applications/Proxyman.app"
dockutil --no-restart --add "/Applications/Xcode.app"
dockutil --no-restart --add "~/Downloads" --section others

###############################################################################
# Finder
###############################################################################

# Always open everything in list view.
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Avoid creating .DS_Store files on network volumes.
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable the warning when changing a file extension.
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# New finder window shows your home folder.
defaults write com.apple.finder NewWindowTarget PfHm

# Show all filename extensions.
defaults write -g  AppleShowAllExtensions -bool true

# Show icons for hard drives, servers, and removable media on the desktop.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Show the ~/Library folder.
chflags nohidden ~/Library

# When performing a search, search the current folder by default.
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

###############################################################################
# General
###############################################################################

# Disable "close windows when quitting an app" (required for iTerm2 3.x).
defaults write -g NSQuitAlwaysKeepsWindows -bool true

# Activate Dark Mode
sudo osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'

###############################################################################
# Keyboard
###############################################################################

# Set a really fast key repeat.
defaults write -g KeyRepeat -int 1

# Set a shorter delay until key repeat.
defaults write -g InitialKeyRepeat -int 12

###############################################################################
# Keyboard Shortcuts
###############################################################################

# Add the keyboard shortcut ⌘⌥↑ to select previous conversation.
defaults write -app Messages NSUserKeyEquivalents -dict-add "Select Previous Conversation" "@~↑"

# Add the keyboard shortcut ⌘⌥↓ to select next conversation.
defaults write -app Messages NSUserKeyEquivalents -dict-add "Select Next Conversation" "@~↓"

# Add the keyboard shortcut ⌘⌥→ to select next tab.
defaults write -g NSUserKeyEquivalents -dict-add "Select Next Tab" -string "@~→"

# Add the keyboard shortcut ⌘⌥← to select previous tab.
defaults write -g NSUserKeyEquivalents -dict-add "Select Previous Tab" -string "@~←"

# Add the keyboard shortcut ⌘⌥→ to show next tab.
defaults write -g NSUserKeyEquivalents -dict-add "Show Next Tab" -string "@~→"

# Add the keyboard shortcut ⌘⌥← to show previous tab.
defaults write -g NSUserKeyEquivalents -dict-add "Show Previous Tab" -string "@~←"

# Add the keyboard shortcut ⌘^F to enter full screen.
defaults write -g NSUserKeyEquivalents -dict-add "Enter Full Screen" -string "@^f"

# Add the keyboard shortcut ⌘^F to exit full screen.
defaults write -g NSUserKeyEquivalents -dict-add "Exit Full Screen" -string "@^f"

###############################################################################
# Menu bar
###############################################################################

# Show battery percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

###############################################################################
# Safari
###############################################################################

# Disable opening ‘safe’ files automatically after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Ask websites not to track me.
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

# Show develop menu.
defaults write com.apple.Safari IncludeDevelopMenu -int 1

###############################################################################
# Spotlight
###############################################################################

defaults write com.apple.spotlight orderedItems -array \
  '{"enabled" = 1;"name" = "APPLICATIONS";}' \
  '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
  '{"enabled" = 1;"name" = "DIRECTORIES";}' \
  '{"enabled" = 1;"name" = "PDF";}' \
  '{"enabled" = 0;"name" = "FONTS";}' \
  '{"enabled" = 0;"name" = "DOCUMENTS";}' \
  '{"enabled" = 0;"name" = "MESSAGES";}' \
  '{"enabled" = 0;"name" = "CONTACT";}' \
  '{"enabled" = 0;"name" = "EVENT_TODO";}' \
  '{"enabled" = 0;"name" = "IMAGES";}' \
  '{"enabled" = 0;"name" = "BOOKMARKS";}' \
  '{"enabled" = 0;"name" = "MUSIC";}' \
  '{"enabled" = 0;"name" = "MOVIES";}' \
  '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
  '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
  '{"enabled" = 0;"name" = "SOURCE";}'

###############################################################################
# System
###############################################################################

# Expand print panel by default.
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# Expand save panel by default.
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# Restart Dock to apply new icons.
killall Dock

# Restart System UI to apply changes.
killall SystemUIServer

# Load new settings before rebuilding the index.
sudo killall mds > /dev/null 2>&1

# Make sure indexing is enabled for the main volume.
sudo mdutil -i on / > /dev/null

# Rebuild the index from scratch.
sudo mdutil -E / > /dev/null

echo "Please reboot to apply all settings."

